options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - id: 'Terraform Init'
    name: 'hashicorp/terraform:latest'
    args: ['init']
    # Optional: Specify working directory if not in root
    # dir: 'terraform/'
  #- id: 'Terraform Plan'
  - id: 'Terraform Destroy'
    name: 'hashicorp/terraform:latest'
    args: ['destroy', '-auto-approve']
  #  args: ['plan', '-out=plan.tfout']
  # Optional: Specify working directory if not in root
  # dir: 'terraform/'

  #- id: 'Terraform Apply'
  #  name: 'hashicorp/terraform:latest'
  #  args: ['apply', 'plan.tfout']
    # This step now proceeds without waiting for manual approval.

artifacts:
  objects:
    location: 'gs://devoteam-app/'
    paths: ['plan.tfout']