# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: 'Terraform Init'
    name: 'hashicorp/terraform:latest'
    args: ['init']
    # dir: 'terraform/'
  - id: 'Terraform Destroy'
    name: 'hashicorp/terraform:latest'
    args: ['destroy', '-auto-approve']


  # Optional: Specify working directory if not in root
  # dir: 'terraform'

    # This step now proceeds without waiting for manual approval.
bjects:
    location: 'gs://devoteam-app/'
    paths: ['plan.tfout']
