options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: 'Terraform Init'
    name: 'hashicorp/terraform:latest'
    args: ['init']
    # Optional: Specify working directory if not in root
    # dir: 'terraform/'

  - id: 'Terraform Destroy'
    name: 'hashicorp/terraform:latest'
    args: ['destroy', '-auto-approve']
    # Automatically approves destruction without interactive confirmation
